/**
 * Static character names — the frontend never fetches these from the DB.
 */
export const CHARACTER_NAMES: string[] = [
  "Sanae Kochiya",
  "Mystia Lorelei",
  "Cirno",
  "Sakuya Izayoi",
  "Byakuren Hijiri",
  "Tewi Inaba",
  "Eirin Yagokoro",
  "Komachi Onozuka",
  "Mokou Fujiwara",
  "Flandre Scarlet",
  "Kogasa Tatara",
  "Nazrin",
  "Meiling Hong",
  "Eiki Shiki",
  "Keine Kamishirasawa",
  "Reisen Inaba",
  "Kaguya Houraisan",
  "Yamame Kurodani",
  "Parsee Mizuhashi",
  "Yuyuko Saigyouji",
  "Yukari Yakumo",
  "Yuka Kazami",
  "Remilia Scarlet",
  "Youmu Konpaku",
  "Hina Kagiyama",
  "Patchouli Knowledge",
  "Reimu Hakurei",
  "Ran Yakumo",
  "Suika Ibuki",
  "Satori Komeiji",
  "Tenshi Hinanawi",
  "Koishi Komeiji",
  "Marisa Kirisame",
  "Nitori Kawashiro",
  "Alice Margatroid",
  "Chen",
  "Daiyousei",
  "Kanako Yasaka",
  "Kisume",
  "Koakuma",
  "Kyouko Kasodani",
  "Minoriko Aki",
  "Nagae Iku",
  "Nue Houjuu",
  "Rin Kaenbyou",
  "Seiga Kaku",
  "Shizuha Aki",
  "Suwako Moriya",
  "Wriggle Nightbug",
  "Yuugi Hoshiguma",
  "Utsuho Reiuji",
];
