import {
  BLUR_ALICE_MARGATROID,
  BLUR_BYAKUREN_HIJIRI,
  BLUR_CHEN,
  BLUR_CIRNO,
  BLUR_DAIYOUSEI,
  BLUR_EIKI_SHIKI,
  BLUR_EIRIN_YAGOKORO,
  BLUR_FLANDRE_SCARLET,
  BLUR_HINA_KAGIYAMA,
  BLUR_KAGUYA_HOURAISAN,
  BLUR_KANAKO_YASAKA,
  BLUR_KEINE_KAMISHIRASAWA,
  BLUR_KISUME,
  BLUR_KOAKUMA,
  BLUR_KOGASA_TATARA,
  BLUR_KOISHI_KOMEIJI,
  BLUR_KOMACHI_ONOZUKA,
  BLUR_KYOUKO_KASODANI,
  BLUR_MARISA_KIRISAME,
  BLUR_MEILING_HONG,
  BLUR_MINORIKO_AKI,
  BLUR_MOKOU_FUJIWARA,
  BLUR_MYSTIA_LORELEI,
  BLUR_NAGAE_IKU,
  BLUR_NAZRIN,
  BLUR_NITORI_KAWASHIRO,
  BLUR_NUE_HOUJUU,
  BLUR_PARSEE_MIZUHASHI,
  BLUR_PATCHOULI_KNOWLEDGE,
  BLUR_RAN_YAKUMO,
  BLUR_REIMU_HAKUREI,
  BLUR_REISEN_INABA,
  BLUR_REMILIA_SCARLET,
  BLUR_RIN_KAENBYOU,
  BLUR_SAKUYA_IZAYOI,
  BLUR_SANAE_KOCHIYA,
  BLUR_SATORI_KOMEIJI,
  BLUR_SEIGA_KAKU,
  BLUR_SHIZUHA_AKI,
  BLUR_SUIKA_IBUKI,
  BLUR_SUWAKO_MORIYA,
  BLUR_TENSHI_HINANAWI,
  BLUR_TEWI_INABA,
  BLUR_UTSUHO_REIUJI,
  BLUR_WRIGGLE_NIGHTBUG,
  BLUR_YAMAME_KURODANI,
  BLUR_YOUMU_KONPAKU,
  BLUR_YUKA_KAZAMI,
  BLUR_YUKARI_YAKUMO,
  BLUR_YUUGI_HOSHIGUMA,
  BLUR_YUYUKO_SAIGYOUJI,
} from "./image-blurs";

export type CharacterThumb = {
  src: string;
  blurDataUrl: string;
};

export const CHARACTER_THUMBS: Record<string, CharacterThumb> = {
  "Alice Margatroid": { src: "/img/characters/Alice_Margatroid.jpg", blurDataUrl: BLUR_ALICE_MARGATROID },
  "Byakuren Hijiri": { src: "/img/characters/Byakuren_Hijiri.jpg", blurDataUrl: BLUR_BYAKUREN_HIJIRI },
  "Chen": { src: "/img/characters/Chen.jpg", blurDataUrl: BLUR_CHEN },
  "Cirno": { src: "/img/characters/Cirno.jpg", blurDataUrl: BLUR_CIRNO },
  "Daiyousei": { src: "/img/characters/Daiyousei.jpg", blurDataUrl: BLUR_DAIYOUSEI },
  "Eiki Shiki": { src: "/img/characters/Eiki_Shiki.jpg", blurDataUrl: BLUR_EIKI_SHIKI },
  "Eirin Yagokoro": { src: "/img/characters/Eirin_Yagokoro.jpg", blurDataUrl: BLUR_EIRIN_YAGOKORO },
  "Flandre Scarlet": { src: "/img/characters/Flandre_Scarlet.jpg", blurDataUrl: BLUR_FLANDRE_SCARLET },
  "Hina Kagiyama": { src: "/img/characters/Hina_Kagiyama.jpg", blurDataUrl: BLUR_HINA_KAGIYAMA },
  "Kaguya Houraisan": { src: "/img/characters/Kaguya_Houraisan.jpg", blurDataUrl: BLUR_KAGUYA_HOURAISAN },
  "Kanako Yasaka": { src: "/img/characters/Kanako_Yasaka.jpg", blurDataUrl: BLUR_KANAKO_YASAKA },
  "Keine Kamishirasawa": { src: "/img/characters/Keine_Kamishirasawa.jpg", blurDataUrl: BLUR_KEINE_KAMISHIRASAWA },
  "Kisume": { src: "/img/characters/Kisume.jpg", blurDataUrl: BLUR_KISUME },
  "Koakuma": { src: "/img/characters/Koakuma.jpg", blurDataUrl: BLUR_KOAKUMA },
  "Kogasa Tatara": { src: "/img/characters/Kogasa_Tatara.jpg", blurDataUrl: BLUR_KOGASA_TATARA },
  "Koishi Komeiji": { src: "/img/characters/Koishi_Komeiji.jpg", blurDataUrl: BLUR_KOISHI_KOMEIJI },
  "Komachi Onozuka": { src: "/img/characters/Komachi_Onozuka.jpg", blurDataUrl: BLUR_KOMACHI_ONOZUKA },
  "Kyouko Kasodani": { src: "/img/characters/Kyouko_Kasodani.jpg", blurDataUrl: BLUR_KYOUKO_KASODANI },
  "Marisa Kirisame": { src: "/img/characters/Marisa_Kirisame.jpg", blurDataUrl: BLUR_MARISA_KIRISAME },
  "Meiling Hong": { src: "/img/characters/Meiling_Hong.jpg", blurDataUrl: BLUR_MEILING_HONG },
  "Minoriko Aki": { src: "/img/characters/Minoriko_Aki.jpg", blurDataUrl: BLUR_MINORIKO_AKI },
  "Mokou Fujiwara": { src: "/img/characters/Mokou_Fujiwara.jpg", blurDataUrl: BLUR_MOKOU_FUJIWARA },
  "Mystia Lorelei": { src: "/img/characters/Mystia_Lorelei.jpg", blurDataUrl: BLUR_MYSTIA_LORELEI },
  "Nagae Iku": { src: "/img/characters/Nagae_Iku.jpg", blurDataUrl: BLUR_NAGAE_IKU },
  "Nazrin": { src: "/img/characters/Nazrin.jpg", blurDataUrl: BLUR_NAZRIN },
  "Nitori Kawashiro": { src: "/img/characters/Nitori_Kawashiro.jpg", blurDataUrl: BLUR_NITORI_KAWASHIRO },
  "Nue Houjuu": { src: "/img/characters/Nue_Houjuu.jpg", blurDataUrl: BLUR_NUE_HOUJUU },
  "Parsee Mizuhashi": { src: "/img/characters/Parsee_Mizuhashi.jpg", blurDataUrl: BLUR_PARSEE_MIZUHASHI },
  "Patchouli Knowledge": { src: "/img/characters/Patchouli_Knowledge.jpg", blurDataUrl: BLUR_PATCHOULI_KNOWLEDGE },
  "Ran Yakumo": { src: "/img/characters/Ran_Yakumo.jpg", blurDataUrl: BLUR_RAN_YAKUMO },
  "Reimu Hakurei": { src: "/img/characters/Reimu_Hakurei.jpg", blurDataUrl: BLUR_REIMU_HAKUREI },
  "Reisen Inaba": { src: "/img/characters/Reisen_Inaba.jpg", blurDataUrl: BLUR_REISEN_INABA },
  "Remilia Scarlet": { src: "/img/characters/Remilia_Scarlet.jpg", blurDataUrl: BLUR_REMILIA_SCARLET },
  "Rin Kaenbyou": { src: "/img/characters/Rin_Kaenbyou.jpg", blurDataUrl: BLUR_RIN_KAENBYOU },
  "Sakuya Izayoi": { src: "/img/characters/Sakuya_Izayoi.jpg", blurDataUrl: BLUR_SAKUYA_IZAYOI },
  "Sanae Kochiya": { src: "/img/characters/Sanae_Kochiya.jpg", blurDataUrl: BLUR_SANAE_KOCHIYA },
  "Satori Komeiji": { src: "/img/characters/Satori_Komeiji.jpg", blurDataUrl: BLUR_SATORI_KOMEIJI },
  "Seiga Kaku": { src: "/img/characters/Seiga_Kaku.jpg", blurDataUrl: BLUR_SEIGA_KAKU },
  "Shizuha Aki": { src: "/img/characters/Shizuha_Aki.jpg", blurDataUrl: BLUR_SHIZUHA_AKI },
  "Suika Ibuki": { src: "/img/characters/Suika_Ibuki.jpg", blurDataUrl: BLUR_SUIKA_IBUKI },
  "Suwako Moriya": { src: "/img/characters/Suwako_Moriya.jpg", blurDataUrl: BLUR_SUWAKO_MORIYA },
  "Tenshi Hinanawi": { src: "/img/characters/Tenshi_Hinanawi.jpg", blurDataUrl: BLUR_TENSHI_HINANAWI },
  "Tewi Inaba": { src: "/img/characters/Tewi_Inaba.jpg", blurDataUrl: BLUR_TEWI_INABA },
  "Utsuho Reiuji": { src: "/img/characters/Utsuho_Reiuji.jpg", blurDataUrl: BLUR_UTSUHO_REIUJI },
  "Wriggle Nightbug": { src: "/img/characters/Wriggle_Nightbug.jpg", blurDataUrl: BLUR_WRIGGLE_NIGHTBUG },
  "Yamame Kurodani": { src: "/img/characters/Yamame_Kurodani.jpg", blurDataUrl: BLUR_YAMAME_KURODANI },
  "Youmu Konpaku": { src: "/img/characters/Youmu_Konpaku.jpg", blurDataUrl: BLUR_YOUMU_KONPAKU },
  "Yuka Kazami": { src: "/img/characters/Yuka_Kazami.jpg", blurDataUrl: BLUR_YUKA_KAZAMI },
  "Yukari Yakumo": { src: "/img/characters/Yukari_Yakumo.jpg", blurDataUrl: BLUR_YUKARI_YAKUMO },
  "Yuugi Hoshiguma": { src: "/img/characters/Yuugi_Hoshiguma.jpg", blurDataUrl: BLUR_YUUGI_HOSHIGUMA },
  "Yuyuko Saigyouji": { src: "/img/characters/Yuyuko_Saigyouji.jpg", blurDataUrl: BLUR_YUYUKO_SAIGYOUJI },
};

export function getThumb(name: string): CharacterThumb | null {
  return CHARACTER_THUMBS[name] ?? null;
}
